---

weka_models:
  func_exact_para_stem_syn_dep: &func_exact_para_stem_syn_dep_models_weka
    en_func_exact_para_stem_syn_dep_weka: $BEER/models/en_func_exact_para_stem_syn_dep_weka
  func_exact_para_stem_syn: &func_exact_para_stem_syn_models_weka
    en_func_exact_para_stem_syn_weka: $BEER/models/en_func_exact_para_stem_syn_weka
  func_exact_para_stem: &func_exact_para_stem_models_weka
    en_func_exact_para_stem_weka: $BEER/models/en_func_exact_para_stem_weka
    fr_func_exact_para_stem_weka: $BEER/models/fr_func_exact_para_stem_weka
    de_func_exact_para_stem_weka: $BEER/models/de_func_exact_para_stem_weka
    es_func_exact_para_stem_weka: $BEER/models/es_func_exact_para_stem_weka
    ru_func_exact_para_stem_weka: $BEER/models/ru_func_exact_para_stem_weka
    other_func_exact_para_stem_weka: $BEER/models/other_func_exact_para_stem_weka
  func_exact_para: &func_exact_para_models_weka
    en_func_exact_para_weka: $BEER/models/en_func_exact_para_weka
    fr_func_exact_para_weka: $BEER/models/fr_func_exact_para_weka
    cs_func_exact_para_weka: $BEER/models/cs_func_exact_para_weka
    de_func_exact_para_weka: $BEER/models/de_func_exact_para_weka
    es_func_exact_para_weka: $BEER/models/es_func_exact_para_weka
    ru_func_exact_para_weka: $BEER/models/ru_func_exact_para_weka
    other_func_exact_para_weka: $BEER/models/other_func_exact_para_weka
  func_exact_stem: &func_exact_stem_models_weka
    en_func_exact_stem_weka: $BEER/models/en_func_exact_stem_weka
    fr_func_exact_stem_weka: $BEER/models/fr_func_exact_stem_weka
    de_func_exact_stem_weka: $BEER/models/de_func_exact_stem_weka
    es_func_exact_stem_weka: $BEER/models/es_func_exact_stem_weka
    ru_func_exact_stem_weka: $BEER/models/ru_func_exact_stem_weka
    other_func_exact_stem_weka: $BEER/models/other_func_exact_stem_weka
  exact: &exact_models_weka
    en_exact_weka: $BEER/models/en_exact_weka
    fr_exact_weka: $BEER/models/fr_exact_weka
    cs_exact_weka: $BEER/models/cs_exact_weka
    de_exact_weka: $BEER/models/de_exact_weka
    es_exact_weka: $BEER/models/es_exact_weka
    ru_exact_weka: $BEER/models/ru_exact_weka
    hi_exact_weka: $BEER/models/hi_exact_weka
    other_exact_weka: $BEER/models/other_exact_weka

RankNet_models:
  func_exact_para_stem_syn_dep: &func_exact_para_stem_syn_dep_models_RankNet
    en_func_exact_para_stem_syn_dep_RankNet: $BEER/models/en_func_exact_para_stem_syn_dep_RankNet
  func_exact_para_stem_syn: &func_exact_para_stem_syn_models_RankNet
    en_func_exact_para_stem_syn_RankNet: $BEER/models/en_func_exact_para_stem_syn_RankNet
  func_exact_para_stem: &func_exact_para_stem_models_RankNet
    en_func_exact_para_stem_RankNet: $BEER/models/en_func_exact_para_stem_RankNet
    fr_func_exact_para_stem_RankNet: $BEER/models/fr_func_exact_para_stem_RankNet
    de_func_exact_para_stem_RankNet: $BEER/models/de_func_exact_para_stem_RankNet
    es_func_exact_para_stem_RankNet: $BEER/models/es_func_exact_para_stem_RankNet
    ru_func_exact_para_stem_RankNet: $BEER/models/ru_func_exact_para_stem_RankNet
    other_func_exact_para_stem_RankNet: $BEER/models/other_func_exact_para_stem_RankNet
  func_exact_para: &func_exact_para_models_RankNet
    en_func_exact_para_RankNet: $BEER/models/en_func_exact_para_RankNet
    fr_func_exact_para_RankNet: $BEER/models/fr_func_exact_para_RankNet
    cs_func_exact_para_RankNet: $BEER/models/cs_func_exact_para_RankNet
    de_func_exact_para_RankNet: $BEER/models/de_func_exact_para_RankNet
    es_func_exact_para_RankNet: $BEER/models/es_func_exact_para_RankNet
    ru_func_exact_para_RankNet: $BEER/models/ru_func_exact_para_RankNet
    other_func_exact_para_RankNet: $BEER/models/other_func_exact_para_RankNet
  func_exact_stem: &func_exact_stem_models_RankNet
    en_func_exact_stem_RankNet: $BEER/models/en_func_exact_stem_RankNet
    fr_func_exact_stem_RankNet: $BEER/models/fr_func_exact_stem_RankNet
    de_func_exact_stem_RankNet: $BEER/models/de_func_exact_stem_RankNet
    es_func_exact_stem_RankNet: $BEER/models/es_func_exact_stem_RankNet
    ru_func_exact_stem_RankNet: $BEER/models/ru_func_exact_stem_RankNet
    other_func_exact_stem_RankNet: $BEER/models/other_func_exact_stem_RankNet
  exact: &exact_models_RankNet
    en_exact_RankNet: $BEER/models/en_exact_RankNet
    fr_exact_RankNet: $BEER/models/fr_exact_RankNet
    cs_exact_RankNet: $BEER/models/cs_exact_RankNet
    de_exact_RankNet: $BEER/models/de_exact_RankNet
    es_exact_RankNet: $BEER/models/es_exact_RankNet
    ru_exact_RankNet: $BEER/models/ru_exact_RankNet
    hi_exact_RankNet: $BEER/models/hi_exact_RankNet
    other_exact_RankNet: $BEER/models/other_exact_RankNet

resources:
  en:
    funcWords:  $METEOR/resources/function/english.words
    synonym:    $METEOR/resources/synonym
    paraphrase: $METEOR/data/paraphrase-en.gz
    stem: yes
    normalization: yes
    models:
      evaluation: $BEER/models/en_func_exact_para_stem_syn_dep_weka
      evaluationNoSyntax: $BEER/models/en_func_exact_para_stem_syn_weka
      tuning: $BEER/models/tuning_en_func_exact_para_stem_syn_weka
      wmttuning: $BEER/models/en_func_exact_para_stem_syn_weka
      evaluationANN: $BEER/models/en_func_exact_para_stem_syn_dep_RankNet
      <<: *func_exact_para_stem_syn_dep_models_weka
      <<: *func_exact_para_stem_syn_models_weka
      <<: *func_exact_para_stem_models_weka
      <<: *func_exact_para_models_weka
      <<: *func_exact_stem_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_stem_syn_dep_models_RankNet
      <<: *func_exact_para_stem_syn_models_RankNet
      <<: *func_exact_para_stem_models_RankNet
      <<: *func_exact_para_models_RankNet
      <<: *func_exact_stem_models_RankNet
      <<: *exact_models_RankNet
      
  fr:
    funcWords:  $METEOR/resources/function/french.words
    paraphrase: $METEOR/data/paraphrase-fr.gz
    stem: yes
    normalization: yes
    models:
      evaluation: $BEER/models/fr_func_exact_para_stem_weka
      evaluationANN: $BEER/models/fr_func_exact_para_stem_RankNet
      <<: *func_exact_para_stem_models_weka
      <<: *func_exact_para_models_weka
      <<: *func_exact_stem_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_stem_models_RankNet
      <<: *func_exact_para_models_RankNet
      <<: *func_exact_stem_models_RankNet
      <<: *exact_models_RankNet
  de:
    funcWords:  $METEOR/resources/function/german.words
    paraphrase: $METEOR/data/paraphrase-de.gz
    stem: yes
    normalization: yes
    models:
      evaluation: $BEER/models/de_func_exact_para_stem_weka
      evaluationANN: $BEER/models/de_func_exact_para_stem_RankNet
      <<: *func_exact_para_stem_models_weka
      <<: *func_exact_para_models_weka
      <<: *func_exact_stem_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_stem_models_RankNet
      <<: *func_exact_para_models_RankNet
      <<: *func_exact_stem_models_RankNet
      <<: *exact_models_RankNet
  es:
    funcWords:  $METEOR/resources/function/spanish.words
    paraphrase: $METEOR/data/paraphrase-es.gz
    stem: yes
    normalization: yes
    models:
      evaluation: $BEER/models/es_func_exact_para_stem_weka
      evaluationANN: $BEER/models/es_func_exact_para_stem_RankNet
      <<: *func_exact_para_stem_models_weka
      <<: *func_exact_para_models_weka
      <<: *func_exact_stem_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_stem_models_RankNet
      <<: *func_exact_para_models_RankNet
      <<: *func_exact_stem_models_RankNet
      <<: *exact_models_RankNet
  ru:
    funcWords:  $METEOR/resources/function/russian.words
    paraphrase: $METEOR/data/paraphrase-ru.gz
    stem: yes
    normalization: yes
    models:
      evaluation: $BEER/models/ru_func_exact_para_stem_weka
      evaluationANN: $BEER/models/ru_func_exact_para_stem_RankNet
      <<: *func_exact_para_stem_models_weka
      <<: *func_exact_para_models_weka
      <<: *func_exact_stem_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_stem_models_RankNet
      <<: *func_exact_para_models_RankNet
      <<: *func_exact_stem_models_RankNet
      <<: *exact_models_RankNet
  cs:
    funcWords:  $METEOR/resources/function/czech.words
    paraphrase: $METEOR/data/paraphrase-cz.gz
    normalization: yes
    models:
      evaluation: $BEER/models/cs_func_exact_para_weka
      wmttuning: $BEER/models/cs_func_exact_para_weka
      evaluationANN: $BEER/models/cs_func_exact_para_RankNet
      <<: *func_exact_para_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_models_RankNet
      <<: *exact_models_RankNet
  ur:
    funcWords:  $BEER/resources/urdu/function.words
    paraphrase: $BEER/resources/urdu/paraphrase.gz
    models:
      evaluation: $BEER/models/other_func_exact_para_weka
      evaluationANN: $BEER/models/other_func_exact_para_RankNet
      <<: *func_exact_para_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_models_RankNet
      <<: *exact_models_RankNet
  ar:
    funcWords:  $BEER/resources/arabic/function.words
    paraphrase: $BEER/resources/arabic/paraphrase.gz
    models:
      evaluation: $BEER/models/other_func_exact_para_weka
      evaluationANN: $BEER/models/other_func_exact_para_RankNet
      <<: *func_exact_para_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_models_RankNet
      <<: *exact_models_RankNet
  ja:
    funcWords:  $BEER/resources/japanese/function.words
    paraphrase: $BEER/resources/japanese/paraphrase.gz
    models:
      evaluation: $BEER/models/other_func_exact_para_weka
      evaluationANN: $BEER/models/other_func_exact_para_RankNet
      <<: *func_exact_para_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_models_RankNet
      <<: *exact_models_RankNet
  da:
    funcWords:  $METEOR/resources/function/danish.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  fi:
    funcWords:  $METEOR/resources/function/finnish.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  hu:
    funcWords:  $METEOR/resources/function/hungarian.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
  it:
    funcWords:  $METEOR/resources/function/italian.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  nl:
    funcWords:  $METEOR/resources/function/dutch.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  no:
    funcWords:  $METEOR/resources/function/norwegian.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  pt:
    funcWords:  $METEOR/resources/function/portuguese.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  ro:
    funcWords:  $METEOR/resources/function/romanian.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  se:
    funcWords:  $METEOR/resources/function/swediush.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  tr:
    funcWords:  $METEOR/resources/function/turkish.words
    stem: yes
    models:
      evaluation: $BEER/models/other_func_exact_stem_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet
  other:
    funcWords:  $METEOR/resources/function/other.words
    models:
      evaluation: $BEER/models/other_exact_weka
      wmttuning: $BEER/models/other_exact_weka
      evaluationANN: $BEER/models/other_func_exact_stem_RankNet
      <<: *func_exact_para_stem_syn_dep_models_weka
      <<: *func_exact_para_stem_syn_models_weka
      <<: *func_exact_para_stem_models_weka
      <<: *func_exact_para_models_weka
      <<: *func_exact_stem_models_weka
      <<: *exact_models_weka
      <<: *func_exact_para_stem_syn_dep_models_RankNet
      <<: *func_exact_para_stem_syn_models_RankNet
      <<: *func_exact_para_stem_models_RankNet
      <<: *func_exact_para_models_RankNet
      <<: *func_exact_stem_models_RankNet
      <<: *exact_models_RankNet
  hi:
    funcWords:  $METEOR/resources/function/other.words
    models:
      evaluation: $BEER/models/hi_exact_weka
      evaluationANN: $BEER/models/hi_exact_RankNet
      <<: *exact_models_weka
      <<: *exact_models_RankNet

